function pomiary2 = importfile(filename, dataLines)
%IMPORTFILE3 Import data from a text file
%  POMIARY2 = IMPORTFILE3(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  POMIARY2 = IMPORTFILE3(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  pomiary2 = importfile3("J:\Uczelnia\MGR\Sem2\ES2\ES_IMU\Madgwick\pomiary2.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Dec-2020 18:47:09

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Var1", "AccX", "AccY", "AccZ", "Var5", "GyroX", "GyroY", "GyroZ"];
opts.SelectedVariableNames = ["AccX", "AccY", "AccZ", "GyroX", "GyroY", "GyroZ"];
opts.VariableTypes = ["string", "double", "double", "double", "string", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var5"], "EmptyFieldRule", "auto");

% Import the data
pomiary2 = readtable(filename, opts);

end