function capture = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  CAPTURE = IMPORTFILE1(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  CAPTURE = IMPORTFILE1(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  capture = importfile1("J:\Uczelnia\MGR\Sem2\ES2\ES_IMU\Madgwick\capture.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Jan-2021 17:17:44

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Var1", "Temp", "Var3", "AccX", "AccY", "AccZ", "Var7", "GyroX", "GyroY", "GyroZ", "Var11", "EulX", "EulY", "EulZ"];
opts.SelectedVariableNames = ["Temp", "AccX", "AccY", "AccZ", "GyroX", "GyroY", "GyroZ", "EulX", "EulY", "EulZ"];
opts.VariableTypes = ["string", "double", "string", "double", "double", "double", "string", "double", "double", "double", "string", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var3", "Var7", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var3", "Var7", "Var11"], "EmptyFieldRule", "auto");

% Import the data
capture = readtable(filename, opts);

end